<<<<<<< HEAD
<?xml version="1.0" encoding="UTF-16"?>
<!-- This file is generated by XMLToHTMLSetup. Any changes you make
     to the file will be lost the next time XMLToHTMLSetup is run. -->
<xsl:stylesheet xmlns:xsl = "http://www.w3.org/1999/XSL/Transform"
                version = "1.0">
  <xsl:import href = "C:\mamlSchema\Maml_HTML_Style.xsl"/>
</xsl:stylesheet>
=======
<?xml version="1.0" encoding="UTF-16"?>
<!-- This file is generated by XMLToHTMLSetup. Any changes you make
     to the file will be lost the next time XMLToHTMLSetup is run. -->
<xsl:stylesheet xmlns:xsl = "http://www.w3.org/1999/XSL/Transform"
                version = "1.0">
  <xsl:import href = "C:\mamlSchema\Maml_HTML_Style.xsl"/>
</xsl:stylesheet>
>>>>>>> 94e7240e4017e5ff163804c12cc582d2f8092628
